### PR TITLE
Fix current control

### PR DESCRIPTION
**Pull request by JimmyDaSilva**
As I was trying to make the current mode working for my DC motor (#9), I found out that the values of the commands were never wrote.

Now it works !

### CODE REVIEW

**Comment by velinddimitrov** [comment]
Jimmy: This is tested, right? I can merge it in?

**Comment by JimmyDaSilva** [comment]
Hi @velinddimitrov. I was only able to test it with one DC motor but I guess it should work for others too.

**Comment by velinddimitrov** [comment]
Ok, thx. I will merge it in. Re: your other pull request, I want to change a few things but i will merge that in as well. Sorry for the delay.

**Comment by JimmyDaSilva** [comment]
@velinddimitrov Awesome ! Thank you

**Pull request merged**
